export enum Authority {
  VIEW_LOGS = "VIEW_LOGS",
  VIEW_PROCESSES = "VIEW_PROCESSES",
  VIEW_USERS = "VIEW_USERS",
  EDIT_USERS = "EDIT_USERS",
  KILL_PROCESSES = "KILL_PROCESSES",
  VIEW_LOGIN_PAGE = "VIEW_LOGIN_PAGE",
  VIEW_SETTINGS = "VIEW_SETTINGS"
}
